version: '3'

services:
  es_service:
    image: elasticsearch:8.10.2
    environment:
      - 'cluster.name=docker-cluster'
      - 'bootstrap.memory_lock=true'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  es_data:
    driver: local
