FROM python:3.10

RUN apt update

WORKDIR /sprint-4

COPY requirements.txt requirements.txt

RUN  pip install --upgrade pip \
     && pip install -r requirements.txt --no-cache-dir

COPY . .

# Укажите, как запускать ваш сервис
RUN ["python3", "src/main.py"]
