version: '3'

services:
  es_service:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    env_file:
      - src/core/.env
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
      - 'cluster.name=docker-cluster'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - backend

  redis_service:
    image: redis
    expose:
      - 6379
    networks:
      - backend

  async_api:
    build: .
    env_file:
      - src/core/.env
    depends_on:
      - es_service
      - redis_service
    networks:
      - backend
    ports:
      - "8000:8000"

volumes:
  es_data:
    driver: local

networks:
  backend:
    driver: bridge
