version: '3'

services:
  es_service:
    image: elasticsearch:8.9.1
    env_file:
      - src/core/.env
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
      - 'cluster.name=docker-cluster'
      - 'bootstrap.memory_lock=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    expose:
      - 9200
    networks:
      - backend

  redis_service:
    image: redis
    expose:
      - 6379
    networks:
      - backend

  async_api:
    build: .
    env_file:
      - src/core/.env
    depends_on:
      - es_service
      - redis_service
    expose:
      - 8000
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./nginx/data:/data/:ro
      - ./nginx/logs:/var/log/nginx/
    depends_on:
      - async_api
    ports:
      - '80:80'
    networks:
      - backend

volumes:
  es_data:
    driver: local

networks:
  backend:
    driver: bridge
