version: '3'

services:
  es_service:
    image: elasticsearch:8.9.1
    env_file:
      - src/core/.env
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    expose:
      - 9200

  redis_service:
    image: redis
    expose:
      - 6379

  async_api:
    build: .
    env_file:
      - src/.env_example
    depends_on:
      - es_service
      - redis_service
    ports:
      - "8000:8000"
